# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-piSAMBaq8ade5Tzr6uxUxa-aDrx1QP
"""

import pandas as pd
baza={
    "FISH":[ " Muhammadaliyev Oybek ", "Boltaboyeva Asal","Ismatov Toshmat","Ikromaliyeva Sevara","Adashaliyev Abdullo","Qobulov Umidjon","Qobulova Sarvinoz","Shermamatova Qoriyabonu" , "Habibjonova Farzona","Dehqonov Alisher"],
    "Yoshi" :[ ' 18  ','19' ,'17','16','13','18','17','19' , '12', '10'],
    "Maktab" : [ ' 55-maktab', '3-maktab', '265-maktab', '123-maktab','21-maktab', '56-maktab','32-maktab','76-maktab','211-maktab','121-maktab'],
    "Jinsi" :[ "o'g'il bola" , "qiz bola","o'g'il bola","qiz bola","o'g'il bola","o'g'il bola","qiz bola","qiz bola","qiz bola","o'g'il bola"],
    "Manzili" :[ ' Namangan viloyat ', 'Qashqadaryo viloyat' ,'Toshkent viloyat','Jizzax viloyat','Fargona viloyat', 'Toshkent shahar', 'Shaxrixon tuman',"chust tuman",'Namangan viloyat', 'Besh ariq']

}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']== "o'g'il bola"]
print(filtr)

filtr=db[(db['Jinsi']=="o'g'il bola") & (db['Manzili']==" Namangan viloyat ")]
print(filtr)